# Etapa 1: Construcción
FROM gradle:8.7-jdk21 AS build
WORKDIR /app
COPY back /app
RUN gradle clean build --no-daemon

# Etapa 2: Ejecución
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]