version: "3.9"

services:
  backend:
    build: .
    container_name: saludvital-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    image: nginx:stable-alpine
    container_name: saludvital-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
