# Etapa 1: Construcción
FROM gradle:8.7-jdk21 AS build
WORKDIR /app
COPY backend /app
RUN ./gradlew --no-daemon --retry 3 clean build -x test


# Etapa 2: Ejecución
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
