name: Build, Test & Deploy SaludVital

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      #  Obtener el código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar JDK 21
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # dar permisos a dradle en el runner
      - name: Grant execute permission for gradlew
        run: chmod +x back/gradlew


      # Configurar Gradle cache
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}
          restore-keys: gradle-

      #  Compilar y ejecutar tests Java
      - name: Build and run tests
        working-directory: back
        run: ./gradlew clean test --no-daemon

      #   Placeholder para pruebas de rendimiento
      # - name: Run performance tests
      #   run: ./gradlew performanceTest --no-daemon

      # Instalar Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Setear token
      - name: Set RAILWAY_TOKEN
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      # Despliegue
      - name: Deploy SaludVital
        run: railway up --service SaludVital --detach

