name: Deploy SaludVital to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      
      - name: Set RAILWAY_TOKEN
        run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

      # despliegue
      - name: Deploy SaludVital
        run: |
          cd back  # si tu Dockerfile está en back/
          railway up --detach
